# Generated by Django 6.0.2 on 2026-02-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(choices=[('suite', 'Suite'), ('deluxe', 'Deluxe Room'), ('standard', 'Standard Room')], max_length=100)),
                ('pricePerNight', models.IntegerField(default=150)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('NPR', 'Nepalese Rupee')], default='NPR', max_length=10)),
                ('maxOccupancy', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
