# Generated by Django 6.0.2 on 2026-03-18 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occupieddates',
            unique_together={('room', 'date')},
        ),
    ]
